# Generated by Django 4.0.1 on 2022-02-09 15:27

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('name', models.TextField(null=True)),
                ('surname', models.TextField(null=True)),
                ('school', models.TextField(null=True)),
                ('DOB', models.DateField(null=True)),
                ('password', models.TextField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_date')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='update_date')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RobotController',
            fields=[
                ('controller_id', models.AutoField(primary_key=True, serialize=False)),
                ('controller_name', models.TextField(null=True)),
                ('lastest_command', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_date')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='update_date')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('lab_id', models.AutoField(primary_key=True, serialize=False)),
                ('lab_name', models.TextField(null=True)),
                ('code', models.CharField(max_length=4, null=True)),
                ('date_time_slot', models.DateTimeField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_date')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='update_date')),
                ('user_controller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_date')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='update_date')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lab_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labex.lab')),
            ],
        ),
    ]
