# Generated by Django 4.0.1 on 2022-04-24 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='robot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labex.robotcontroller'),
        ),
    ]
